base_url: http://localhost:11434
model: qwen3:4b-instruct
system_prompt: You are a helpful assistant.
parameters:
  num_ctx: 8192
  temperature: 0.7
  num_predict: -1
  top_k: 20
  top_p: 0.95
  min_p: 0.05