embedder:
  url: https://api.siliconflow.cn/v1/embeddings
  api_key: <your_api_key>
  model: BAAI/bge-m3
generator:
  host: http://localhost:11434
  model: gemma3:12b
  system_content: You are a helpful assistant.
  options:
    num_ctx: 8192
    temperature: 0.7
    num_predict: -1
    top_k: 20
    top_p: 0.95
    min_p: 0.05
reranker:
  url: https://api.siliconflow.cn/v1/rerank
  api_key: <your_api_key>
  model: BAAI/bge-reranker-v2-m3
  top_k: 3
retriever:
  n_results: 5
vector_db:
    collection_name: my_collection
